language: julia
codecov: true
os:
- linux
julia:
- 1.0
- 1.1
notifications:
  email: false
branches:
  only:
  - master
  - "/^release-.*$/"
env:
  global:
    secure: DlLHJfhnRTodFqT1vbxkX5qwaSPKX5geq09kewkmk4TE1COFMeJXfH2KzpXCpKy0BREYuk5ZCDp5zNsYspNKzRt3Libl9Utz948NKcYSDgKRPAfvqs8Y5R57/TQvcvq6Y5UYPQ4USnktfEuXLCmJeGrnp1WtXUpvD5h6RjHgeKk=
